export const CONSTANTS = {
    API_URL:"https://api.openweathermap.org/data/2.5/weather?q=",
    API_KEY: "fd48bdf8a8b87b3c140f17625f4e2d57",
    cities: [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia",
        "San Antonio",
        "San Diego",
        "Dallas",
        "San Jose",
        "Austin",
        "Jacksonville",
        "Fort Worth",
        "Columbus",
        "San Francisco",
        "Charlotte",
        "Indianapolis",
        "Seattle",
        "Denver",
        "Washington D.C.",
        "Boston",
        "El Paso",
        "Nashville",
        "Detroit",
        "Oklahoma City",
        "Portland",
        "Las Vegas",
        "Louisville",
        "Baltimore",
        "Milwaukee",
        "Albuquerque",
        "Tucson",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Kansas City",
        "Mesa",
        "Virginia Beach",
        "Atlanta",
        "Colorado Springs",
        "Omaha",
        "Raleigh",
        "Miami",
        "Cleveland",
        "Tulsa",
        "Oakland",
        "Minneapolis",
        "Wichita",
        "Arlington",
        "New Orleans",
        "Bakersfield",
        "Tampa",
        "Honolulu",
        "Anaheim",
        "Santa Ana",
        "St. Louis",
        "Pittsburgh",
        "Corpus Christi",
        "Cincinnati",
        "Anchorage",
        "Lexington",
        "Stockton",
        "St. Paul",
        "Buffalo",
        "Chula Vista",
        "Fort Wayne",
        "Chandler",
        "Overland Park",
        "Garland",
        "Glendale",
        "Hialeah",
        "Riverside",
        "Scottsdale",
        "Newark",
        "Bakersfield",
        "Baton Rouge",
        "Richmond",
        "Boise",
        "Des Moines",
        "Spokane",
        "San Bernardino",
        "Modesto",
        "Fontana",
        "Santa Clarita",
        "Santa Rosa",
        "Henderson",
        "Aurora",
        "Bridgeport",
        "Grand Rapids",
        "Atlanta",
        "Tallahassee",
        "Columbus",
        "Montgomery"
    ]
}   